import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AboutPage from "./about/page";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="container mx-auto h-[calc(100vh-7rem)] flex justify-center items-center">
            {children}
        </main>
      </body>
    </html>
  );
}
